import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const pageUrl = new URL("../app/page.tsx", import.meta.url);
const stylesUrl = new URL("../app/responsive.css", import.meta.url);

test("connected scene UI never falls back to demo data", async () => {
  const source = await readFile(pageUrl, "utf8");
  assert.match(source, /XIAOMI_DEVICE_HTTP_\$\{response\.status\}/, "deployment HTML errors must not leak JSON parser messages");
  assert.match(source, /connection\.connected\?\(selectedHome==="demo"\?\[\]:sceneState\.items\):demoScenes/);
  assert.match(source, /connection\.connected\)void loadScenes\(homeId\)/, "switching homes must load that home's scenes");
  assert.match(source, /URLSearchParams\(\{includeScenes:"1"\}\)/, "device sync must include the selected home's scenes in the same request");
  assert.doesNotMatch(source, /await loadDevices\(true\);await loadScenes/, "manual sync must not issue a second scene request");
  assert.match(source, /setDevices\(\[\]\);setHomes\(\[\]\);setSelectedHome\(""\)/, "a failed first live sync must not leave demo devices visible");
});

test("sync UI deduplicates requests, caches scenes, and cools down retryable failures", async () => {
  const source = await readFile(pageUrl, "utf8");
  assert.match(source, /syncInFlight=useRef<Promise<void>\|null>/);
  assert.match(source, /deviceLoadInFlight=useRef<Promise<string>\|null>/);
  assert.match(source, /sceneRequests=useRef\(new Map<string,Promise<void>>\(\)\)/);
  assert.match(source, /if\(!force&&scenesByHome\[homeId\]\?\.loaded\)return/);
  assert.match(source, /if\(syncInFlight\.current\)return syncInFlight\.current/);
  assert.match(source, /if\(deviceLoadInFlight\.current\)return deviceLoadInFlight\.current/);
  assert.match(source, /beginSyncCooldown\(error\.retryAfterSeconds\)/);
  assert.match(source, /lastSuccessfulSync/);
  assert.match(source, /syncWarningSummary\(syncWarnings\)/);
  assert.match(source, /部分设备状态待确认/);
});

test("scene cards represent loading, empty, error and duplicate-execution states", async () => {
  const source = await readFile(pageUrl, "utf8");
  assert.match(source, /正在读取米家场景/);
  assert.match(source, /当前家庭没有可用的手动场景/);
  assert.match(source, /场景读取失败/);
  assert.match(source, /if\(!scene\.enabled\|\|sceneOperating\)return/);
  assert.match(source, /disabled=\{!scene\.enabled\|\|blocked\}/);
});

test("scene cards open details and use a separate execution button", async () => {
  const source = await readFile(pageUrl, "utf8");
  const styles = await readFile(stylesUrl, "utf8");
  const start = source.indexOf("function SceneCard");
  const end = source.indexOf("function SceneStateMessage", start);
  const sceneCard = source.slice(start, end);
  assert.match(sceneCard, /className="scene-card-open"[^>]*onClick=\{onOpen\}/s);
  assert.match(sceneCard, /className="scene-run"[^>]*onClick=\{\(\)=>onRun\(scene\)\}/s);
  assert.match(sceneCard, /connected\?"执行":"演示"/);
  assert.match(sceneCard, /running\?"执行中…"/);
  assert.match(source, /connected\?"执行场景":"执行演示"/);
  assert.doesNotMatch(sceneCard, /runScene\(/, "the card component must not execute a scene from its detail action");
  assert.match(source, /selectedScene\?<SceneDetailPage/, "opening a card must show a normal scene-detail page");
  assert.match(source, /function SceneDetailPage/);
  assert.match(source, /className="scene-page"/);
  assert.doesNotMatch(source, /selectedScene&&<div className="modal-bg"/, "scene details must not use a modal");
  assert.match(source, /className="scene-modal-run"/, "the detail card must expose an explicit execution action");
  assert.doesNotMatch(sceneCard, /触发方式与条件|手动点击/, "manual triggers should not occupy scene detail space");
  assert.match(sceneCard, /className="scene-action-list"/);
  assert.match(sceneCard, /groupManualSceneActions\(actions,devices\)/, "actions must be grouped using current-home devices");
  assert.match(sceneCard, /className="scene-action-groups"/);
  assert.match(sceneCard, /groups\.map\(group=>/);
  assert.match(sceneCard, /group\.rooms\.map\(room=>/, "rooms must be nested inside matching property groups");
  assert.match(sceneCard, /className="scene-action-room"/);
  assert.match(sceneCard, /item\.kind==="light-batch"/, "identical light batches must use the folded presentation");
  assert.match(sceneCard, /scene-action-detail \$\{detail\.kind\}/, "action properties must receive semantic styling hooks");
  assert.match(sceneCard, /style=\{sceneActionDetailStyle\(detail\)\}/, "numeric light values must control their visual treatment");
  assert.match(sceneCard, /sceneActionDetailGlyph\(detail\)/, "action properties must have recognizable icons");
  assert.match(source, /制冷\|cool/);
  assert.match(source, /制热\|heat/);
  assert.match(source, /目标温度\|温度\|temperature/);
  assert.match(source, /送风\|风速\|风量\|fan/);
  assert.match(source, /编辑场景/);
  assert.match(source, /新建场景/);
  assert.match(styles, /\.scene-action-detail\.power\.on/);
  assert.match(styles, /\.scene-action-detail\.power\.off/);
  assert.match(styles, /\.scene-action-detail\.brightness/);
  assert.match(styles, /\.scene-action-detail\.color-temperature/);
  assert.match(styles, /--scene-detail-level/, "brightness and temperature styles must expose their numeric level");
  assert.match(source, /\(numeric-2700\)\/\(6500-2700\)/, "color temperature must map from warm to cool");
  assert.match(sceneCard, /formatSceneTime\(scene\.updatedAt\)/, "raw Xiaomi timestamps should be formatted for people");
});

test("scene editor supports safe create and update workflows", async () => {
  const source = await readFile(new URL("../app/scene-editor.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/scene-editor.css", import.meta.url), "utf8");
  assert.match(source, /method:sceneId\?"PUT":"POST"/);
  assert.match(source, /revision:draft\.revision/);
  assert.match(source, /actionsEditable/);
  assert.match(source, /动作保持只读/);
  assert.match(source, /放弃尚未保存的场景修改/);
  assert.match(source, /设置属性/);
  assert.match(source, /动作编辑模式/);
  assert.match(source, /单设备/);
  assert.match(source, /批量修改/);
  assert.match(source, /\/api\/xiaomi\/scenes\/action-catalog/);
  assert.match(source, /Supported actions/);
  assert.match(source, /rawLabels/);
  assert.match(source, /singleDeviceRoom/);
  assert.match(source, /singleDeviceKind/);
  assert.match(source, /单设备按房间筛选/);
  assert.match(source, /单设备按类型筛选/);
  assert.match(source, /<optgroup key=\{room\} label=\{room\}>/, "single-device results must be grouped by room");
  assert.match(styles, /\.scene-single-filters\{grid-template-columns:1fr/, "single-device filters must appear before the target selector");
  assert.match(source, /indices\.length>1\?"batch":"single"/, "folded actions must default to batch while single actions use the official catalog");
  assert.match(source, /按房间筛选/);
  assert.match(source, /按类型筛选/);
  assert.match(source, /className="scene-device-options" role="listbox"/);
  assert.match(source, /aria-multiselectable="true"/);
  assert.match(source, /selectedTargetKeys\.includes\(option\.key\)/);
  assert.match(source, /targetOptionKey\(device\.did,preferredService\)/, "repeated services must expose concrete switch-button targets");
  assert.match(source, /byModel=new Map<string,Promise<Specification>>/, "capabilities should be deduplicated by model");
  assert.match(source, /mapScenePropertySemantics\(selectedSemantics,specification\.groups,preferredService,device\.did\)/, "targets must be filtered by selected properties, values, and concrete repeated service");
  assert.match(source, /mapScenePropertySemantics\(semantics,specification\.groups,option\.preferredService,device\.did\)/, "batch properties must map by MIoT semantic name and target device");
  assert.match(source, /没有对应的枚举选项/);
  assert.match(source, /枚举选项名称不唯一/);
  assert.match(source, /semanticValueKey:`enum:\$\{semantics\[index\]\.choice\.key\}`/, "device-specific enum values must fold by their shared semantic label");
  assert.match(source, /source\?\.sourceIndex/, "editing a folded group must preserve source action identities");
  assert.match(source, /isLightGroup\(device\)\?"灯组"/, "light groups must be visible as targets");
  assert.doesNotMatch(source, /!\/\^group\\\.\*\/i/, "light groups must not be excluded from editable targets");
  assert.match(source, /listSceneWritableProperties\(group\)/, "scene UI must consume the shared safe property projection");
  assert.doesNotMatch(source, /group\.properties\.filter\(property=>property\.writable/);
  assert.doesNotMatch(source, />执行动作</);
  assert.match(source, /moveAction/);
  assert.match(source, /className="scene-editor scene-editor-page"/);
  assert.doesNotMatch(source, /className="modal-bg scene-editor-bg"/, "scene creation and editing must be normal pages");
  assert.match(source, /\{!composerOpen&&<>/, "the scene form and action step must be mutually exclusive");
  assert.match(source, /composerOpen&&<section className=\{`scene-action-composer scene-action-page/, "adding or editing an action must use its own step");
  assert.match(source, /onClick=\{composerOpen\?cancelComposer:close\}/, "the action-step back button must return to the scene form");
  assert.match(source, /actionGroups\.map\(group=>/);
  assert.match(source, /group\.rooms\.map\(room=>/, "the editor must group properties before rooms");
  assert.match(source, /groupIndices=group\.rooms\.flatMap/, "group editing must collect every action across room sections");
  assert.match(source, /groupActions=groupIndices\.flatMap\(index=>\{const action=draft\.actions\[index\]/, "group editing must use raw draft actions rather than display projections");
  assert.match(source, /semanticValueKey:`enum:\$\{semantics\[index\]\.choice\.key\}`/, "enum grouping must use a stable semantic key");
  assert.match(source, /catalogTemplate=actionCatalog\.find/, "existing scenes must resolve display names through the official action catalog");
  assert.match(source, /displayValue:catalogTemplate\?\.label\|\|semantics\[index\]\.choice\.label/, "enum groups must prefer the matched official localized action name");
  assert.match(source, /if\(!composerOpen&&!sceneId\)return/, "existing scene summaries must load the official catalog before action editing starts");
  assert.match(source, /groupEditable=groupActions\.length===group\.actionCount/, "single and batch property groups must share the same edit eligibility");
  assert.match(source, /className="scene-group-tools"/, "every editable property group must expose one shared edit control");
  assert.doesNotMatch(source, /startEdit\(action,item\.indices\)/, "room items must not duplicate property edit controls");
  assert.match(styles, /\.scene-group-tools/, "the shared group edit control must be styled");
  assert.match(source, /switchGroup\?\{deviceName:`\$\{device\?\.name\?\?action\.deviceName\} · \$\{switchGroup\.label\}`/, "switch actions must identify their concrete device and button outside the property-group name");
  assert.match(styles, /@media\(max-width:760px\)/);
  assert.match(styles, /env\(safe-area-inset-bottom\)/);
});

test("real execution reports submission without speculative device updates", async () => {
  const source = await readFile(pageUrl, "utf8");
  const start = source.indexOf("async function runScene");
  const end = source.indexOf("function openLogin", start);
  const runScene = source.slice(start, end);
  assert.match(runScene, /已下发到米家云/);
  assert.doesNotMatch(runScene.slice(runScene.indexOf("setSceneOperating(scene.id)")), /setDevices/, "connected execution must not change device state");
});
