"use client";

import { useEffect, useMemo, useState } from "react";
import type { ManagedDevice } from "../lib/device-management";
import type { AutomationEditorDraft } from "../lib/xiaomi-automation-editor";
import type { XiaomiAutomation } from "../lib/xiaomi-automations";
import type { SceneDraftAction, SceneValue } from "../lib/xiaomi-scene-editor";

type Props = { homeId: string; homeName: string; devices: ManagedDevice[]; connected: boolean; onMessage: (message: string) => void };
type CatalogAction = { key:string;kind:"set-property";did:string;deviceName:string;room:string;model:string;serviceLabel:string;siid:number;piid:number;label:string;format:string;range?:{min:number;max:number;step:number};choices?:Array<{value:SceneValue;label:string}> };
type TriggerTemplate = { key:string;automationId:string;sourceIndex:number;kind:string;label:string;detail?:string };
type Catalog = { actions: CatalogAction[]; triggerKinds:Array<{kind:string;label:string;writable:boolean}>;triggerTemplates:TriggerTemplate[] };
type EditorState = AutomationEditorDraft & { schedule?:{time:string;weekdays:number[]}; actions:Array<SceneDraftAction|{clientId:string;kind:"unsupported";sourceIndex:number;label:string;deviceName?:string;reason:string}> };

const demoAutomations:XiaomiAutomation[]=[
  {id:"demo-sunset",homeId:"demo",name:"傍晚回家亮灯",enabled:true,triggerMode:"all",triggers:[{kind:"weather",label:"日落后",editable:false},{kind:"location",label:"有人回家",editable:false}],actions:[{order:1,label:"打开",deviceName:"玄关灯",details:[{kind:"power",label:"电源",value:"开启",state:"on"}]}],actionCount:1},
  {id:"demo-night",homeId:"demo",name:"深夜自动晚安",enabled:false,triggerMode:"all",triggers:[{kind:"schedule",label:"每天 23:30",time:"23:30",weekdays:[1,2,3,4,5,6,7],editable:true}],actions:[{order:1,label:"关闭",deviceName:"全屋灯具",details:[{kind:"power",label:"电源",value:"关闭",state:"off"}]}],actionCount:1},
];

function friendlyError(error:string){return ({XIAOMI_AUTOMATION_CONFLICT:"自动化已在米家 App 或其他页面中修改，请返回列表后重试。",XIAOMI_AUTOMATION_TRIGGER_READ_ONLY:"这个触发条件由米家或设备插件管理，当前只能原样保留。",XIAOMI_AUTOMATION_ACTIONS_READ_ONLY:"自动化包含暂不支持重建的动作，动作区保持只读。",XIAOMI_AUTOMATION_WRITE_NOT_VISIBLE:"米家云已接收请求，但暂时没有回读到一致结果。",XIAOMI_AUTOMATION_NAME_CONFLICT:"当前家庭已有同名自动化。"} as Record<string,string>)[error]||`自动化操作失败：${error}`}
function actionValue(option:CatalogAction):SceneValue{if(option.format==="bool")return true;if(option.choices?.length)return option.choices[0]!.value;if(option.range)return option.range.min;return ""}
function triggerGlyph(kind:string){return kind==="schedule"?"◷":kind==="device"?"▣":kind==="location"?"⌖":kind==="weather"?"☀":"◇"}

export default function AutomationCenter({homeId,homeName,connected,onMessage}:Props){
  const [items,setItems]=useState<XiaomiAutomation[]>(connected?[]:demoAutomations),[loading,setLoading]=useState(connected),[error,setError]=useState(""),[selected,setSelected]=useState<XiaomiAutomation|null>(null),[editorId,setEditorId]=useState<string|undefined|null>(null),[draft,setDraft]=useState<EditorState>(),[catalog,setCatalog]=useState<Catalog>({actions:[],triggerKinds:[],triggerTemplates:[]}),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[actionKey,setActionKey]=useState("");
  const rooms=useMemo(()=>Array.from(new Set(catalog.actions.map(item=>item.room))),[catalog.actions]);
  const [actionRoom,setActionRoom]=useState("");
  const actionOptions=useMemo(()=>catalog.actions.filter(item=>!actionRoom||item.room===actionRoom),[actionRoom,catalog.actions]);

  async function load(){if(!connected||!homeId||homeId==="demo"){setItems(demoAutomations);setLoading(false);return}setLoading(true);setError("");try{const response=await fetch(`/api/xiaomi/automations?homeId=${encodeURIComponent(homeId)}`),data=await response.json();if(!response.ok)throw new Error(data.error||"XIAOMI_AUTOMATION_SYNC_FAILED");setItems(Array.isArray(data.automations)?data.automations:[]);setSelected(current=>current?(data.automations as XiaomiAutomation[]).find(item=>item.id===current.id)??null:null)}catch(reason){setError(reason instanceof Error?reason.message:"UNKNOWN_ERROR")}finally{setLoading(false)}}
  useEffect(()=>{if(!connected||!homeId||homeId==="demo")return;let active=true;void fetch(`/api/xiaomi/automations?homeId=${encodeURIComponent(homeId)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"XIAOMI_AUTOMATION_SYNC_FAILED");if(active){setItems(Array.isArray(data.automations)?data.automations:[]);setLoading(false)}}).catch(reason=>{if(active){setError(reason instanceof Error?reason.message:"UNKNOWN_ERROR");setLoading(false)}});return()=>{active=false}},[homeId,connected]);

  async function openEditor(id?:string){if(!connected)return;setEditorId(id??"");setDirty(false);setError("");try{const catalogRequest=fetch(`/api/xiaomi/automations/catalog?homeId=${encodeURIComponent(homeId)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);return data as Catalog});const next=id?fetch(`/api/xiaomi/automations/${encodeURIComponent(id)}?homeId=${encodeURIComponent(homeId)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);return data.draft as EditorState}):Promise.resolve({sceneId:"",homeId,name:"",enabled:false,revision:"",actionsEditable:true,actions:[],triggerEditable:true,triggerLabel:"尚未选择条件",triggerMode:"any",triggerSelections:[]} as EditorState);const [loadedCatalog,loadedDraft]=await Promise.all([catalogRequest,next]);setCatalog({...loadedCatalog,triggerTemplates:loadedCatalog.triggerTemplates??[]});setDraft(loadedDraft)}catch(reason){setError(reason instanceof Error?reason.message:"UNKNOWN_ERROR")}}
  function closeEditor(){if(!dirty||window.confirm("放弃尚未保存的自动化修改？")){setEditorId(null);setDraft(undefined)}}
  function update(patch:Partial<EditorState>){if(!draft)return;setDraft({...draft,...patch});setDirty(true)}
  function toggleDay(day:number){if(!draft?.schedule)return;const days=draft.schedule.weekdays.includes(day)?draft.schedule.weekdays.filter(item=>item!==day):[...draft.schedule.weekdays,day].sort();if(days.length)update({schedule:{...draft.schedule,weekdays:days}})}
  function toggleSchedule(){if(!draft)return;update({schedule:draft.schedule?undefined:{time:"08:00",weekdays:[1,2,3,4,5,6,7]}})}
  function toggleTriggerTemplate(template:TriggerTemplate){if(!draft)return;const selections=draft.triggerSelections??[],selected=selections.some(item=>item.automationId===template.automationId&&item.sourceIndex===template.sourceIndex);update({triggerSelections:selected?selections.filter(item=>item.automationId!==template.automationId||item.sourceIndex!==template.sourceIndex):[...selections,{automationId:template.automationId,sourceIndex:template.sourceIndex}]})}
  function addAction(){if(!draft)return;const option=catalog.actions.find(item=>item.key===actionKey);if(!option)return;const value=actionValue(option);const action:SceneDraftAction={clientId:crypto.randomUUID(),kind:"set-properties",did:option.did,deviceName:option.deviceName,model:option.model,label:`设置${option.label}`,properties:[{siid:option.siid,piid:option.piid,value,label:option.label}]};update({actions:[...draft.actions,action]});setActionKey("")}
  function removeAction(index:number){if(!draft?.actionsEditable)return;update({actions:draft.actions.filter((_,item)=>item!==index)})}
  function setPropertyValue(index:number,value:SceneValue){if(!draft)return;const actions=draft.actions.map((action,item)=>item===index&&action.kind==="set-properties"?{...action,properties:action.properties?.map((property,propertyIndex)=>propertyIndex?property:{...property,value})}:action);update({actions})}
  async function save(){if(!draft?.name.trim()||!draft.actions.length||!draft.schedule&&!(draft.triggerSelections?.length)||draft.schedule&&!draft.schedule.weekdays.length)return;setSaving(true);setError("");try{const editing=Boolean(editorId),body={homeId,name:draft.name.trim(),enabled:draft.enabled,schedule:draft.schedule,triggerSelections:draft.triggerSelections,triggerMode:draft.triggerMode,...(editing?{revision:draft.revision}:{}),...(draft.actionsEditable?{actions:draft.actions.filter((action):action is SceneDraftAction=>action.kind!=="unsupported")}:{})};const response=await fetch(editing?`/api/xiaomi/automations/${encodeURIComponent(editorId!)}?homeId=${encodeURIComponent(homeId)}`:"/api/xiaomi/automations",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error||"XIAOMI_AUTOMATION_SAVE_FAILED");setDirty(false);setEditorId(null);setDraft(undefined);setSelected(data.automation as XiaomiAutomation);await load();onMessage(`${data.automation.name}${editing?"已更新":"已创建"}`)}catch(reason){setError(reason instanceof Error?reason.message:"UNKNOWN_ERROR")}finally{setSaving(false)}}

  if(editorId!==null)return <AutomationEditor draft={draft} error={error} saving={saving} triggerKinds={catalog.triggerKinds} triggerTemplates={catalog.triggerTemplates} rooms={rooms} actionRoom={actionRoom} actionOptions={actionOptions} actionKey={actionKey} onClose={closeEditor} onUpdate={update} onToggleSchedule={toggleSchedule} onToggleTriggerTemplate={toggleTriggerTemplate} onToggleDay={toggleDay} onActionRoom={setActionRoom} onActionKey={setActionKey} onAddAction={addAction} onRemoveAction={removeAction} onPropertyValue={setPropertyValue} onSave={()=>void save()}/>;
  if(selected)return <AutomationDetail automation={selected} homeName={homeName} connected={connected} onBack={()=>setSelected(null)} onEdit={()=>void openEditor(selected.id)}/>;
  const active=items.filter(item=>item.enabled),inactive=items.filter(item=>!item.enabled);
  return <section className="automation-center" aria-label="自动化中心"><header><div><span>AUTOMATION</span><h2>智能自动化</h2><p>{homeName} · 让设备按条件自动响应</p></div><button type="button" disabled={!connected||homeId==="demo"} onClick={()=>void openEditor()}>＋ 新建自动化</button></header>{!connected&&<div className="automation-notice">当前展示米家风格演示数据；扫码连接后会读取当前家庭的真实自动化。</div>}{loading&&<div className="automation-state">正在读取米家自动化…</div>}{error&&<div className="automation-state error" role="alert">{friendlyError(error)} <button onClick={()=>void load()}>重试</button></div>}{!loading&&!error&&!items.length&&<div className="automation-empty"><span>⌁</span><strong>还没有自动化</strong><p>添加条件与动作，让家在合适的时间自动响应。</p></div>}<AutomationGroup title="正在运行" items={active} onOpen={setSelected}/><AutomationGroup title="已停用" items={inactive} onOpen={setSelected}/></section>
}

function AutomationGroup({title,items,onOpen}:{title:string;items:XiaomiAutomation[];onOpen:(item:XiaomiAutomation)=>void}){if(!items.length)return null;return <section className="automation-group"><header><strong>{title}</strong><small>{items.length} 条</small></header><div>{items.map(item=><button type="button" className="automation-card" key={item.id} onClick={()=>onOpen(item)}><span className={`automation-status ${item.enabled?"on":"off"}`}><i/></span><div><strong>{item.name}</strong><small>{item.triggers.map(trigger=>trigger.label).join(item.triggerMode==="all"?" 且 ":" 或 ")}</small><p>{item.actions.slice(0,2).map(action=>action.deviceName||action.label).join("、")||`${item.actionCount} 个动作`}</p></div><b>›</b></button>)}</div></section>}

function AutomationDetail({automation,homeName,connected,onBack,onEdit}:{automation:XiaomiAutomation;homeName:string;connected:boolean;onBack:()=>void;onEdit:()=>void}){return <section className="automation-detail"><header><button onClick={onBack}>← 返回自动化</button>{connected&&<button className="primary" onClick={onEdit}>编辑自动化</button>}</header><div className="automation-detail-title"><span>⌁</span><div><small>{automation.enabled?"正在运行":"已停用"}</small><h2>{automation.name}</h2><p>{homeName}</p></div></div><AutomationFlow automation={automation}/></section>}
function AutomationFlow({automation}:{automation:XiaomiAutomation}){return <div className="automation-flow"><section><header><span>IF</span><div><strong>满足以下条件</strong><small>{automation.triggerMode==="all"?"全部满足":"任一满足"}</small></div></header>{automation.triggers.map((trigger,index)=><div className="automation-flow-row" key={`${trigger.kind}:${index}`}><i>{triggerGlyph(trigger.kind)}</i><div><strong>{trigger.label}</strong>{trigger.detail&&<small>{trigger.detail}</small>}</div>{!trigger.editable&&<em>只读</em>}</div>)}</section><b className="automation-flow-link">↓</b><section><header><span>THEN</span><div><strong>执行以下动作</strong><small>按顺序执行</small></div></header>{automation.actions.map((action,index)=><div className="automation-flow-row" key={index}><i>{index+1}</i><div><strong>{action.deviceName||action.label}</strong><small>{action.details.map(detail=>`${detail.label} ${detail.value}`).join(" · ")||action.label}</small></div></div>)}</section></div>}

function AutomationEditor({
  draft,error,saving,triggerKinds,triggerTemplates,rooms,actionRoom,actionOptions,actionKey,onClose,onUpdate,onToggleSchedule,onToggleTriggerTemplate,onToggleDay,onActionRoom,onActionKey,onAddAction,onRemoveAction,onPropertyValue,onSave,
}:{
  draft?:EditorState;error:string;saving:boolean;triggerKinds:Catalog["triggerKinds"];triggerTemplates:TriggerTemplate[];rooms:string[];actionRoom:string;actionOptions:CatalogAction[];actionKey:string;
  onClose:()=>void;onUpdate:(patch:Partial<EditorState>)=>void;onToggleSchedule:()=>void;onToggleTriggerTemplate:(template:TriggerTemplate)=>void;onToggleDay:(day:number)=>void;onActionRoom:(room:string)=>void;
  onActionKey:(key:string)=>void;onAddAction:()=>void;onRemoveAction:(index:number)=>void;
  onPropertyValue:(index:number,value:SceneValue)=>void;onSave:()=>void;
}){
  if(!draft)return <section className="automation-editor"><div className="automation-state">正在准备自动化编辑器…</div>{error&&<div className="automation-state error">{friendlyError(error)}</div>}</section>;
  const selectedTemplates=triggerTemplates.filter(template=>draft.triggerSelections?.some(item=>item.automationId===template.automationId&&item.sourceIndex===template.sourceIndex));
  const triggerCount=(draft.schedule?1:0)+(draft.triggerSelections?.length??0);
  const saveDisabled=saving||!draft.name.trim()||!draft.actions.length||!triggerCount||Boolean(draft.schedule&&!draft.schedule.weekdays.length);
  return <section className="automation-editor automation-editor-single" aria-label={draft.sceneId?"修改自动化":"新建自动化"}>
    <header><button onClick={onClose}>← 返回自动化</button><div><span>AUTOMATION</span><h2>{draft.sceneId?"编辑自动化":"新建自动化"}</h2></div></header>
    <div className="automation-editor-body">
      <section className="automation-editor-section">
        <div className="automation-section-copy"><b>01</b><div><strong>基本信息</strong><p>设置名称与启用状态。新建规则默认关闭。</p></div></div>
        <label className="automation-field"><span>自动化名称</span><input maxLength={50} value={draft.name} placeholder="例如：回家后打开玄关灯" onChange={event=>onUpdate({name:event.target.value})}/></label>
        <label className="automation-enable"><div><strong>启用自动化</strong><small>确认条件和动作无误后再开启</small></div><button type="button" role="switch" aria-checked={draft.enabled} className={draft.enabled?"on":""} onClick={()=>onUpdate({enabled:!draft.enabled})}><i/></button></label>
      </section>
      <section className="automation-editor-section">
        <div className="automation-section-copy"><b>02</b><div><strong>触发条件</strong><p>像米家 App 一样选择时间、设备、日出日落、天气或位置，可组合多个条件。</p></div></div>
        <div className="automation-trigger-mode" aria-label="条件关系"><button type="button" className={draft.triggerMode==="any"?"selected":""} aria-pressed={draft.triggerMode==="any"} onClick={()=>onUpdate({triggerMode:"any"})}>任一条件满足</button><button type="button" className={draft.triggerMode==="all"?"selected":""} aria-pressed={draft.triggerMode==="all"} onClick={()=>onUpdate({triggerMode:"all"})}>全部条件满足</button><small>已选择 {triggerCount} 个条件</small></div>
        <div className="automation-trigger-kinds">{triggerKinds.map(kind=>{const templates=triggerTemplates.filter(item=>item.kind===kind.kind||(kind.kind==="sun"&&item.kind==="weather"&&/日出|日落/.test(item.label)));const isSchedule=kind.kind==="schedule";return <section className="automation-trigger-kind" key={kind.kind}><header><i>{triggerGlyph(kind.kind)}</i><div><strong>{kind.label}</strong><small>{isSchedule?"按指定时间和星期触发":templates.length?`${templates.length} 个当前家庭真实条件`:"当前家庭暂无可复用条件"}</small></div>{isSchedule&&<button type="button" className={draft.schedule?"selected":""} aria-pressed={Boolean(draft.schedule)} onClick={onToggleSchedule}>{draft.schedule?"已选择":"选择"}</button>}</header>{isSchedule&&draft.schedule&&<label className="automation-time"><span>指定时间</span><input type="time" value={draft.schedule.time} onChange={event=>onUpdate({schedule:{...draft.schedule!,time:event.target.value}})}/></label>}{!isSchedule&&templates.length>0&&<div className="automation-trigger-templates">{templates.map(template=>{const selected=draft.triggerSelections?.some(item=>item.automationId===template.automationId&&item.sourceIndex===template.sourceIndex);return <button type="button" key={template.key} className={selected?"selected":""} aria-pressed={selected} onClick={()=>onToggleTriggerTemplate(template)}><span>{template.label}</span>{template.detail&&<small>{template.detail}</small>}<b>{selected?"✓":"＋"}</b></button>})}</div>}</section>})}</div>
      </section>
      <section className="automation-editor-section">
        <div className="automation-section-copy"><b>03</b><div><strong>生效日期</strong><p>设置自动化在哪些星期生效。</p></div></div>
        {draft.schedule?<><div className="automation-weekdays">{["一","二","三","四","五","六","日"].map((label,index)=><button type="button" className={draft.schedule!.weekdays.includes(index+1)?"selected":""} aria-pressed={draft.schedule!.weekdays.includes(index+1)} onClick={()=>onToggleDay(index+1)} key={label}>周{label}</button>)}</div><div className="automation-period"><span>生效时段</span><strong>全天</strong><small>使用中国标准时间（Asia/Shanghai）</small></div></>:<div className="automation-readonly"><strong>不使用指定时间</strong><p>设备、天气和位置条件会沿用其米家原始参数。</p></div>}
      </section>
      <section className="automation-editor-section">
        <div className="automation-section-copy"><b>04</b><div><strong>执行动作</strong><p>动作按顺序执行，只提供规格明确公开的安全设置。</p></div></div>
        <div className="automation-action-list">{draft.actions.map((action,index)=><div key={action.clientId} className={action.kind==="unsupported"?"readonly":""}><b>{index+1}</b><div><strong>{action.deviceName||action.label}</strong><small>{action.kind==="unsupported"?action.reason:action.properties?.map(property=>property.label||String(property.siid)+"."+String(property.piid)).join(" · ")}</small>{action.kind==="set-properties"&&action.properties?.[0]&&<SimpleValue action={action} index={index} onChange={onPropertyValue}/>}</div>{draft.actionsEditable&&<button onClick={()=>onRemoveAction(index)}>删除</button>}</div>)}</div>
        {draft.actionsEditable&&<div className="automation-add-action"><select value={actionRoom} onChange={event=>onActionRoom(event.target.value)}><option value="">全部房间</option>{rooms.map(room=><option value={room} key={room}>{room}</option>)}</select><select value={actionKey} onChange={event=>onActionKey(event.target.value)}><option value="">选择设备和设置</option>{actionOptions.map(option=><option value={option.key} key={option.key}>{option.room} · {option.deviceName} · {option.label}</option>)}</select><button type="button" disabled={!actionKey} onClick={onAddAction}>加入动作</button></div>}
      </section>
      <section className="automation-editor-section automation-editor-summary">
        <div className="automation-section-copy"><b>05</b><div><strong>保存检查</strong><p>米家云回读完全一致后才报告成功。</p></div></div>
        <div className="automation-review-flow"><div><b>IF</b><strong>{[...(draft.schedule?[`${draft.schedule.time} · ${draft.schedule.weekdays.length===7?"每天":"每周 "+draft.schedule.weekdays.join("、")}`]:[]),...selectedTemplates.map(item=>item.label)].join(draft.triggerMode==="all"?" 且 ":" 或 ")||"尚未选择条件"}</strong></div><div><b>THEN</b><strong>{draft.actions.length} 个动作</strong></div></div>
      </section>
      {error&&<div className="automation-state error" role="alert">{friendlyError(error)}</div>}
    </div>
    <footer><button onClick={onClose}>取消</button><button className="primary" disabled={saveDisabled} onClick={onSave}>{saving?"正在保存并回读…":draft.sceneId?"保存修改":"创建自动化"}</button></footer>
  </section>
}
function SimpleValue({action,index,onChange}:{action:SceneDraftAction;index:number;onChange:(index:number,value:SceneValue)=>void}){const property=action.properties?.[0];if(!property)return null;if(typeof property.value==="boolean")return <button type="button" className={`automation-value-switch ${property.value?"on":""}`} onClick={()=>onChange(index,!property.value)}>{property.value?"开启":"关闭"}</button>;return <input className="automation-value-input" value={String(property.value)} onChange={event=>onChange(index,typeof property.value==="number"?Number(event.target.value):event.target.value)}/>}
