"use client";
import { useEffect, useMemo, useState } from "react";
type Device={id:number;entityId?:string;name:string;room:string;kind:string;icon:string;on:boolean;status:string;detail:string;color:string};
type Connection={loading:boolean;connected:boolean;name?:string;version?:string;error?:string};
const seed:Device[]=[
{id:1,name:"客厅吸顶灯",room:"客厅",kind:"灯光",icon:"☀",on:true,status:"已开启",detail:"亮度 68% · 暖白",color:"orange"},{id:2,name:"米家空调",room:"客厅",kind:"环境",icon:"❄",on:true,status:"制冷中",detail:"24°C · 自动风",color:"blue"},{id:3,name:"扫拖机器人",room:"客厅",kind:"清洁",icon:"◎",on:false,status:"充电中",detail:"电量 86% · 基站",color:"green"},{id:4,name:"床头灯",room:"主卧",kind:"灯光",icon:"♢",on:false,status:"已关闭",detail:"离线控制可用",color:"violet"},{id:5,name:"空气净化器",room:"主卧",kind:"环境",icon:"≈",on:true,status:"自动模式",detail:"PM2.5 处于优",color:"cyan"},{id:6,name:"智能门锁",room:"玄关",kind:"安防",icon:"▣",on:true,status:"已上锁",detail:"电量 72%",color:"slate"}];
const rooms=["全屋","客厅","主卧","厨房","玄关"];
export default function Home(){
const[devices,setDevices]=useState(seed),[room,setRoom]=useState("全屋"),[tab,setTab]=useState("首页"),[toast,setToast]=useState(""),[authOpen,setAuthOpen]=useState(false),[connection,setConnection]=useState<Connection>({loading:true,connected:false});
const shown=useMemo(()=>room==="全屋"?devices:devices.filter(d=>d.room===room),[devices,room]);
const toggle=async(id:number)=>{const device=devices.find(d=>d.id===id);if(!device)return;const next=!device.on;setDevices(ds=>ds.map(d=>d.id===id?{...d,on:next,status:next?"已开启":"已关闭"}:d));if(device.entityId){const response=await fetch("/api/ha/control",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entityId:device.entityId,turnOn:next})});if(!response.ok){setDevices(ds=>ds.map(d=>d.id===id?{...d,on:!next,status:!next?"已开启":"已关闭"}:d));setToast("控制失败，请检查 Home Assistant 连接");setTimeout(()=>setToast(""),2500)}}};
const run=(name:string)=>{setToast(`${name} 已执行`);if(name==="离家")setDevices(ds=>ds.map(d=>d.kind==="灯光"||d.kind==="环境"?{...d,on:false,status:"已关闭"}:d));setTimeout(()=>setToast(""),2200)};
const sync=async()=>{setConnection(c=>({...c,loading:true}));try{const status=await fetch("/api/ha/status");const info=await status.json();if(!status.ok)throw new Error(info.error);const response=await fetch("/api/ha/entities");const data=await response.json();if(!response.ok)throw new Error(data.error);const icons:Record<string,string>={light:"☀",switch:"ϟ",fan:"≈",climate:"❄",cover:"▥",lock:"▣",vacuum:"◎",humidifier:"◌",media_player:"▷",sensor:"↗",binary_sensor:"◈",scene:"✦"};const controllable=new Set(["light","switch","fan","climate","cover","lock","vacuum","humidifier","media_player"]);const mapped:Device[]=data.entities.filter((e:{domain:string})=>controllable.has(e.domain)).map((e:{entityId:string;name:string;domain:string;state:string;temperature?:number;battery?:number},i:number)=>({id:i+100,entityId:e.entityId,name:e.name,room:"Home Assistant",kind:e.domain,icon:icons[e.domain]||"◈",on:!["off","unavailable","unknown","locked","docked","idle"].includes(e.state),status:e.state==="unavailable"?"离线":e.state,detail:e.temperature!=null?`${e.temperature}°C`:e.battery!=null?`电量 ${e.battery}%`:`实体 · ${e.domain}`,color:["orange","blue","green","violet","cyan"][i%5]}));if(mapped.length)setDevices(mapped);setConnection({loading:false,connected:true,name:info.name,version:info.version});setAuthOpen(false);setToast(`已同步 ${mapped.length} 个可控设备`);setTimeout(()=>setToast(""),2500)}catch(error){setConnection({loading:false,connected:false,error:error instanceof Error?error.message:"UNKNOWN_ERROR"});setAuthOpen(true)}};
useEffect(()=>{void sync()},[]);
return <main className="shell">
<aside className="sidebar"><div className="brand"><b>mi</b><div><strong>我的家</strong><small>{connection.connected?connection.name:"Home Assistant"}</small></div></div><nav>{[["首页","⌂"],["设备","▦"],["场景","✦"],["自动化","⌁"],["能耗","ϟ"]].map(([x,i])=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}><i>{i}</i>{x}</button>)}</nav><div className="sidefoot"><div className={`mode ${connection.connected?"connected":""}`}><span/><div><strong>{connection.loading?"正在连接":connection.connected?"Home Assistant 已连接":"演示模式"}</strong><small>{connection.connected?`Core ${connection.version}`:"配置连接后同步真实设备"}</small></div></div><button className="settings" onClick={()=>setAuthOpen(true)}>⚙　连接设置</button><div className="profile"><b>R</b><div><strong>Ryan</strong><small>家庭管理员</small></div><i>⋯</i></div></div></aside>
<section className="workspace"><header><div><p>2026年8月25日 · 星期二</p><h1>{tab==="首页"?"早上好，Ryan":tab}</h1></div><div className="actions"><button>⌕</button><button>♢</button><button className="primary">＋ 添加设备</button></div></header>
{tab==="首页"||tab==="设备"?<><section className="metrics"><Metric icon="↗" tone="orange" label="室内温度" value="24.6" unit="°C" note="较昨日低 0.8°C"/><Metric icon="◌" tone="blue" label="室内湿度" value="58" unit="%" note="舒适范围"/><Metric icon="≈" tone="green" label="空气质量" value="优" unit="" note="PM2.5 · 8 μg/m³"/><Metric icon="ϟ" tone="violet" label="今日用电" value="6.4" unit=" kWh" note="↓ 12% 较昨日"/></section>
<Title title="快捷场景" sub="轻触即可执行预设" action="管理场景 →"/><section className="scenes">{[["回家","打开客厅灯光与空调","⌂","orange"],["离家","关闭设备并启用安防","↗","blue"],["观影","调暗灯光，关闭窗帘","▷","violet"],["晚安","关闭全屋灯光与家电","☾","indigo"]].map(([n,d,i,c])=><button key={n} onClick={()=>run(n)}><span className={c}>{i}</span><div><strong>{n}</strong><small>{d}</small></div><b>›</b></button>)}</section>
<Title title="我的设备" sub={`${devices.filter(d=>d.on).length} 台运行中 · 1 台离线`} action="查看全部 →"/><div className="rooms">{rooms.map(r=><button key={r} className={room===r?"active":""} onClick={()=>setRoom(r)}>{r}</button>)}</div><section className="devices">{shown.map(d=><article key={d.id}><div className="device-top"><span className={d.color}>{d.icon}</span><button aria-label={`${d.name}${d.on?"关闭":"开启"}`} className={`switch ${d.on?"on":""}`} onClick={()=>toggle(d.id)}><i/></button></div><h3>{d.name}</h3><p>{d.room} · {d.status}</p><div className="detail">{d.detail}<b>›</b></div></article>)}</section></>:tab==="场景"?<Panel title="场景中心" text="集中管理一键场景，让多个设备按预设状态协同工作。"><div className="panel-grid">{["回家","离家","观影","晚安"].map(n=><button key={n} onClick={()=>run(n)}>✦<strong>{n}</strong><small>点击立即执行</small></button>)}</div></Panel>:tab==="自动化"?<Panel title="自动化" text="根据时间、环境和设备状态，让家自动响应。"><Rule a="日落后" b="有人回家" c="打开玄关灯"/><Rule a="每日 23:30" b="门锁已上锁" c="执行晚安"/></Panel>:<Panel title="家庭能耗" text="查看设备用电趋势，发现节能空间。"><div className="chart">{[44,62,52,78,68,90,64].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="labels">{["周一","周二","周三","周四","周五","周六","今天"].map(x=><span key={x}>{x}</span>)}</div></Panel>}</section>
<aside className="rightbar"><div className={`api ${connection.connected?"ha-live":""}`}><div className="api-title"><span>⌁</span><div><strong>Home Assistant</strong><small>{connection.connected?"实时设备连接":"REST API · 安全代理"}</small></div></div><p>{connection.connected?`已连接到 ${connection.name}，设备控制通过 Home Assistant 执行。`:"先在 Home Assistant 安装 Xiaomi Home 集成并完成小米官方 OAuth，再连接本站。"}</p><button onClick={()=>connection.connected?sync():setAuthOpen(true)}>{connection.connected?"立即同步":"配置 Home Assistant"} <b>→</b></button></div><Title title="最近动态" sub="家庭设备实时记录" action="···"/><div className="timeline"><Activity icon="⌂" tone="orange" title="执行「回家」场景" text="3 台设备已响应" time="2 分钟前"/><Activity icon="✓" tone="green" title="智能门锁已上锁" text="通过指纹 · 家庭成员" time="18 分钟前"/><Activity icon="↗" tone="blue" title="空调已调至 24°C" text="自动化 · 舒适温度" time="1 小时前"/><Activity icon="◎" tone="violet" title="扫拖机器人完成清洁" text="清洁 42㎡ · 用时 38 分钟" time="3 小时前"/></div><button className="all">查看全部动态</button><div className="home-status"><div><strong>家庭状态</strong><span>{connection.connected?"实时同步":"演示数据"}</span></div><section><Status icon="◈" n={String(devices.length)} label="可控设备"/><Status icon="ϟ" n={String(devices.filter(d=>d.on).length)} label="运行中"/><Status icon="⌁" n="2" label="自动化"/></section></div></aside>
{authOpen&&<div className="modal-bg" onMouseDown={()=>setAuthOpen(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setAuthOpen(false)}>×</button><span className="ha-logo">HA</span><h2>连接 Home Assistant</h2><p>先在 Home Assistant 的“设备与服务”中添加 <b>Xiaomi Home</b> 并完成小米账号授权，然后为本站配置可远程访问的地址和长期访问令牌。</p><ol className="steps"><li><b>1</b><span>打开 Home Assistant 个人资料，创建长期访问令牌</span></li><li><b>2</b><span>将实例地址与令牌配置为本站的服务器端机密</span></li><li><b>3</b><span>返回这里测试连接并同步设备</span></li></ol><div className="auth-note"><b>服务器端配置项</b><code>HA_BASE_URL</code><code>HA_ACCESS_TOKEN</code>{connection.error&&<em>{friendlyError(connection.error)}</em>}</div><button className="connect-test" onClick={sync} disabled={connection.loading}>{connection.loading?"正在测试连接…":"测试连接并同步"}</button><small>访问令牌只由服务器使用，不会发送到浏览器。</small></div></div>}{toast&&<div className="toast">✓　{toast}</div>}</main>}
function Metric(p:{icon:string;tone:string;label:string;value:string;unit:string;note:string}){return <article><span className={p.tone}>{p.icon}</span><div><small>{p.label}</small><strong>{p.value}<em>{p.unit}</em></strong><p>{p.note}</p></div></article>}
function Title(p:{title:string;sub:string;action:string}){return <div className="title"><div><h2>{p.title}</h2><p>{p.sub}</p></div><button>{p.action}</button></div>}
function Activity(p:{icon:string;tone:string;title:string;text:string;time:string}){return <div className="activity"><span className={p.tone}>{p.icon}</span><div><strong>{p.title}</strong><p>{p.text}</p><small>{p.time}</small></div></div>}
function Status(p:{icon:string;n:string;label:string}){return <span>{p.icon}<b>{p.n}</b><small>{p.label}</small></span>}
function Panel({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <section className="panel"><div className="panel-title"><span>✦</span><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
function Rule({a,b,c}:{a:string;b:string;c:string}){return <div className="rule"><span>{a}</span><b>如果</b><span>{b}</span><b>就</b><span>{c}</span><i>已启用</i></div>}
function friendlyError(error:string){if(error==="HOME_ASSISTANT_NOT_CONFIGURED")return "尚未配置服务器地址或访问令牌";if(error==="HOME_ASSISTANT_HTTP_401")return "访问令牌无效或已过期";if(error==="HOME_ASSISTANT_URL_INVALID")return "Home Assistant 地址格式不正确";return "无法连接 Home Assistant，请检查远程访问地址"}
